on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Srishti Nagraj'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
